@host=http://127.0.0.1:8000
#@host=https://api.lexiai.hdcola.org
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjc4OThmZWVjZDY5OGNkZjg4Yzc4NWY4IiwidXNlcm5hbWUiOiJhbm5hIiwiZW1haWwiOiJhbm5hQG1haWwuY29tIn0.3bfDX-QfaCPOkSEoG9QAe1fWL2VXoZ_AErmQVtTTcDM

### register

POST {{host}}/api/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "anna",
    "email" : "anna@mail.com",
    "password" : "Aa123#"
}

### login
POST {{host}}/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email" : "anna@mail.com",
    "password" : "Aa123#"
}

### get all AI styles
GET {{host}}/api/styles HTTP/1.1


### get all languages
GET {{host}}/api/languages HTTP/1.1

### get all topics for specific language and level
GET {{host}}/api/topics?level=Beginner HTTP/1.1


### get user's settings
GET {{host}}/api/users/settings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### set user's settings
PUT  {{host}}/api/users/settings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "settings": {
    "language_id": "678557da79bc79eeab784fe4",
    "level": "Beginner",
    "topic_id": "67855a2179bc79eeab784fef",
    "style:": "Formal"
  }
}

### update user's settings
PATCH {{host}}/api/users/settings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "settings": {
    "level": "Advanced"
  }
}