@host=http://127.0.0.1:8000

### register

POST {{host}}/api/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "anna",
    "email" : "anna@mail.com",
    "password" : "Aa123#"
}

### login
POST {{host}}/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email" : "anna@mail.com",
    "password" : "Aa123#"
}

### get all AI styles
GET {{host}}/api/styles HTTP/1.1


### get all languages
GET {{host}}/api/languages HTTP/1.1

### get all topics for specific language and level
GET {{host}}/api/topics?level=Beginner HTTP/1.1