@host=http://127.0.0.1:8000
#@host=https://api.lexiai.hdcola.org
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJ1c2VybmFtZSI6InRlc3QiLCJ1c2VyX2lkIjoiNjc5MzdlNDI4ZjFhM2RhZjU4ZWMwY2VhIiwiZXhwIjoxNzM3ODA1Nzc0fQ.EmVU1IY1epbY5BqZ0TsUwR175H44o0bOl3r64VtLisk

### register

POST {{host}}/api/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "email" : "test@mail.com",
    "password" : "Aa123#"
}

### login
POST {{host}}/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email" : "test@mail.com",
    "password" : "Aa123#"
}

### get all AI styles
GET {{host}}/api/styles HTTP/1.1

@style_id=6785601479bc79eeab784ffe
### get style by id
GET {{host}}/api/styles/{{style_id}} HTTP/1.1


### get all languages
GET {{host}}/api/languages HTTP/1.1


### get language by id
@language_id=6785965186ea7bd211eb2f9f
GET {{host}}/api/languages/{{language_id}} HTTP/1.1

### get all topics for level (admin)
GET {{host}}/api/topics?level=Beginner HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### get all topics (admin)
GET {{host}}/api/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### get topic by user_id
GET {{host}}/api/topics?user_id=me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### create topic
POST {{host}}/api/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "Bank",
  "description": "Go to the bank to handle business",
  "level": "Beginner",
  "system_prompt": "Go to the bank to handle business",
  "start": "Hello! How can I help you today?"
}

### get topic by id
@topic_id=6792b5c54782aaaec8bfbddd
GET {{host}}/api/topics/{{topic_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### update topic
PUT {{host}}/api/topics/{{topic_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "Bank",
  "description": "Go to the bank to handle business",
  "level": "Beginner",
  "system_prompt": "You are a bank clerk, and your job is to help customers handle business.",
  "start": "Hello! How can I help you today?"
}

### delete topic
DELETE {{host}}/api/topics/{{topic_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}


### get user's settings
GET {{host}}/api/users/settings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### update user profile
PATCH {{host}}/api/users/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}
{
    "username": "harry1",
    "email" : "harry1@mail.com"
}


### update user profile
PATCH {{host}}/api/users/security HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}
{
    "password": "Aa123#a"
}


### set user's settings
PUT  {{host}}/api/users/settings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "settings": {
    "language_id": "678557da79bc79eeab784fe4",
    "level": "Beginner",
    "topic_id": "67855a2179bc79eeab784fef",
    "style:": "Formal"
  }
}

### update user's settings
PATCH {{host}}/api/users/settings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "settings": {
    "level": "Advanced"
  }
}

### get user's favorities
GET {{host}}/api/users/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### add user's favorities
PATCH {{host}}/api/users/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "favorites": {
    "6787e6958c00c6bd30315c84": true
  }
}